### ISSUE TITLE
Error at mka

### ISSUE THREAD

**Issue by jmrunge** [jungleji/android_device_softwinner_cubieboard1#4]
Hi, 
After running "mka" command, it runs for a quite a while and suddenly it stops with following error:

make: **\* There is no rule to build objective `vendor/cm/proprietary/lib/armeabi/libjackpal-androidterm4.so', required by`/home/jmrunge/data/Proyectos/cb-cm-10.1/out/target/product/cubieboard1/system/lib/libjackpal-androidterm4.so'.  Stop.

Any clue how to solve it?

I'm on Debian 7.8.  Output of java -version:
java version "1.7.0_55"
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)

Kind Regards, 

Juan Martin

**Comment by STPJ** [comment]
Android is made for Java 1.6.
Java 1.7 can't make the same binary.

**Comment by jmrunge** [comment]
Thanks for your response.  Tested now with:

java version "1.6.0_34"
OpenJDK Runtime Environment (IcedTea6 1.13.6) (6b34-1.13.6-1~deb7u1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

and got the same error.  Any other hint?

**Comment by STPJ** [comment]
A quick google :
http://forum.odroid.com/viewtopic.php?f=60&t=5102

I remember that one of the site in the Fetch was now down because of proprietary issues, and if I recall it was related with the sound. I end up downloading the Android Source from another dev board and migrate those files to this project. But this issue may have been fixed as it's been about 2 months since my last compile of it.

**Comment by jmrunge** [comment]
Thanks again! Dont know why, but didnt found that link when did google search :(
In my case, the problem was that device/hardkernel/proprietary/lib/libjackpal-androidterm4.so was replaced by libjackpal-androidterm5.so, so I did a ln -s and voila, it compiled.  
As for the fetch error, I didnt got it this time, but I got it a few days ago when compiling "official" jb from cubieboard and fixed it by changing the manifest to point to AOSP repo.
